CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE images (
    id VARCHAR(255) PRIMARY KEY,
    file_path VARCHAR NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    taken_by VARCHAR,
    taken_where VARCHAR,
    notes TEXT
);